server:
  port: 8001
  servlet:
    encoding:
      charset: UTF-8

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: unishop
    password: korea1234
    url: jdbc:mysql://localhost:3306/unishopdb

  jpa:
    hibernate:
      ddl-auto: none #create:, update, none
    show-sql: true
    open-in-view: true

  servlet:
    multipart:
      file-size-threshold: 1MB
      location: C:/images
      max-file-size: 6MB
      max-request-size: 6MB
